services:
  App\Domain\Repository\:
    resource: '../src/Domain/Repository'
    autowire: true
    autoconfigure: true
  App\DataFixtures\:
    resource: '../src/DataFixtures'
    autowire: true
    autoconfigure: true
    tags: ['doctrine.fixture.orm']
  App\Service\:
    resource: '../src/Service'
    autowire: true
    autoconfigure: true
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
    autowire: true
    autoconfigure: true